#!/usr/bin/python3.11

import os
import sys

filename = sys.argv[1]
flags = [
    "biabduction",
    "bufferoverrun",
    "cost",
    "liveness",
    "loop-hoisting",
    "printf-args",
    "pulse",
    "uninit"
]

os.system(f"infer run {' '.join(['--' + f for f in flags])} -- gcc -c {filename} -o /dev/null")
