#!/usr/bin/python3.11

import sys
import os

filename = sys.argv[1]


# Clang
print("Testing clang:")
os.system(f"scan-build clang -Wall -Werror {filename}")

# gcc
print("\n\n\nTesting gcc:")
os.system(f"gcc -fanalyzer -Werror -Wall {filename}")

# infer
print("\n\n\nTesting infer:")
os.system(f"infer run -- gcc -Werror -Wall {filename}")
